[package]
name = "snoopyfetch"
version = "1.0.0"
edition = "2021"

[dependencies]
sys-info = "0.9"
colored = "2.0.4"
whoami = "1.4.1"
unicode-segmentation = "1.10.1"
regex = "1"
clap = { version = "4.4", features = ["derive"] }
rand = "0.8"
